//  Confidential Source Code Property Toys2Life LLC Colorado 2017
//  www.toys2life.org

using System.IO;
using System.Runtime.CompilerServices;

namespace DialogEngine.Models.Logger
{
    /// <summary>
    /// Model for info message
    /// Extends <see cref="LogMessage"/>
    /// </summary>
    public class InfoMessage : LogMessage
    {
        /// <summary>
        /// Creates instance of InfoMessage
        /// </summary>
        /// <param name="_message">Message text</param>
        /// <param name="_file">Autogenerated file name</param>
        /// <param name="_line">Autogenerated line in file</param>
        public InfoMessage(string _message, [CallerFilePath] string _file = "", [CallerLineNumber] int _line = 0) : base(_message)
        {
            SourceFile = Path.GetFileName(_file);
            Line = _line;
        }
    }
}
