//  Confidential Source Code Property Toys2Life LLC Colorado 2017
//  www.toys2life.org

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;

namespace DialogEngine.Models.Logger
{
    /// <summary>
    /// Model for warning message
    /// Extends <see cref="LogMessage"/>
    /// </summary>
    public class WarningMessage : LogMessage
    {
        /// <summary>
        /// Create instance of WarningMessage
        /// </summary>
        /// <param name="_message">Message text</param>
        /// <param name="_file">Autogenerated file name</param>
        /// <param name="_line">Autogenerated line in file</param>
        public WarningMessage(string _message,[CallerFilePath] string _file = "", [CallerLineNumber] int _line = 0) : base(_message)
        {
            SourceFile = Path.GetFileName(_file);
            Line = _line;
        }

    }
}
